# Generated by Django 5.2.4 on 2025-07-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('violation_type', models.CharField(max_length=100)),
                ('violation_datetime', models.DateTimeField()),
                ('violation_image_url', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
